version: "2"
services:
  app:
    container_name: login-example
    image: mamtabhardwaj12/login-example
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-login
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
